### ISSUE TITLE
WHATWG translations

### ISSUE THREAD

**Issue by annevk** [triple-underscore/triple-underscore.github.io#1]
I noticed you have a great set of translations of WHATWG standards. Would you mind if they were linked from the English version? E.g., https://notifications.spec.whatwg.org/ points to a Simplified Chinese translation. It would be great for https://url.spec.whatwg.org/, https://dom.spec.whatwg.org/, etc. to point to their Japanese translation I think. What do you think?

**Comment by triple-underscore** [comment]
Do-u-mo, Anne-san. 

Yes, it is welcom.
WHATWG’s specs I currently have trnaslated (with links targeted to the translated pages) are:

[DOM](https://triple-underscore.github.io/DOM4-ja.html),
[URL](https://triple-underscore.github.io/URL-ja.html),
[Encoding](https://triple-underscore.github.io/Encoding-ja.html),
[Fetch](https://triple-underscore.github.io/Fetch-ja.html),
[XHR](https://triple-underscore.github.io/XHR-ja.html),
[Streams](https://triple-underscore.github.io/Streams-ja.html),
[JavaScript, aka. Web ECMAScript](https://triple-underscore.github.io/javascript-ja.html), and
some of HTML’s spec chapters or sections (workers.html, dom.html, etc.).

For now, these are updated regularly to follow WHATWG’s specs,
and carefully checked as far as I can.

(Note: These pages have a function to switch words in Japanese to in English and vice-versa, located at the bottom-left of the window.
(Though, this function is intended for Japanese users who want to know terms in English. ) )

**Comment by domenic** [comment]
Wow, you're even up to date with the latest---very large---changes to Streams! This is awesome! I'll definitely add a link from the top of Streams tomorrow.

**Comment by annevk** [comment]
I have added a link to XMLHttpRequest: https://xhr.spec.whatwg.org/. If that looks good I'll add it to the remaining standards.

**Comment by triple-underscore** [comment]
That’s ok. Looks good.

**Comment by annevk** [comment]
Great, I think I have covered them all now. Submitted a pull request for whatwg/javascript since I'm not sure if @mathiasbynens would appreciate me editing that document directly.

Thanks so much for doing this, I'm sure the Japanese community appreciates this a lot. If you translate more documents in the future, please don't hesitate to tell us about them, we'd love to work together.

**Comment by triple-underscore** [comment]
Added Japanese translation of Compatibility Standard:
https://compat.spec.whatwg.org/
at:
https://triple-underscore.github.io/compat-ja.html

**Comment by annevk** [comment]
@miketaylr ^^

**Comment by miketaylr** [comment]
Whoa, awesome @triple-underscore! Just filed https://github.com/whatwg/compat/issues/60 to add the link.

**Comment by triple-underscore** [comment]
Added Japanese translation of Infra Standard:
https://infra.spec.whatwg.org/
at:
https://triple-underscore.github.io/infra-ja.html

**Comment by triple-underscore** [comment]
Added Japanese translation of Storage Standard:
https://storage.spec.whatwg.org/
at:
https://triple-underscore.github.io/storage-ja.html

**Comment by annevk** [comment]
Wow, thanks! Added a link: https://github.com/whatwg/storage/commit/76988d20c9df868b111517f406846cd0f9a98240.

**Comment by triple-underscore** [comment]
Added Japanese translation of Console Standard:
https://console.spec.whatwg.org/
at:
https://triple-underscore.github.io/console-ja.html

**Comment by domenic** [comment]
Awesome! @domfarolino, do you want to add a link to console.spec.whatwg.org?

**Comment by domfarolino** [comment]
Sure @domenic will do thanks for the heads up!

**Comment by triple-underscore** [comment]
Added two Japanese translations of:

Fullscreen API:
https://fullscreen.spec.whatwg.org/
at:
https://triple-underscore.github.io/fullscreen-ja.html

Notifications API:
https://notifications.spec.whatwg.org/
at:
https://triple-underscore.github.io/notifications-ja.html

**Comment by annevk** [comment]
Thanks @triple-underscore, that's great! I suspect we'll have them both linked somewhere next week. We're changing some templates around and it's a bit of a coordination puzzle so that's why there's some delay.

**Comment by triple-underscore** [comment]
Added Japanese translation of MIME sniffing:
https://mimesniff.spec.whatwg.org/
at:
https://triple-underscore.github.io/mimesniff-ja.html
(Some of the sections (WebM, MP3 without ID3) are not translated yet.)

**Comment by annevk** [comment]
\o/ created https://github.com/whatwg/mimesniff/pull/62 to link it.

**Comment by triple-underscore** [comment]
Added Japanese translation of Web IDL:
https://webidl.spec.whatwg.org/
at:
https://triple-underscore.github.io/WebIDL-ja.html
https://triple-underscore.github.io/WebIDL-JS-ja.html

The translation of § ECMAScript binding is separated to the latter URL.
(These are available before the spec was turned into a Living Standard.)

**Comment by annevk** [comment]
Thanks @triple-underscore! I'll link to the first document as I see that itself links the second document. See https://github.com/whatwg/webidl/pull/1036.

**Comment by triple-underscore** [comment]
Added Japanese translation of WebSockets:
https://websockets.spec.whatwg.org/
at:
https://triple-underscore.github.io/WebSocket-ja.html

**Comment by domenic** [comment]
Awesome, thank you! I sent https://github.com/whatwg/websockets/pull/11, although I think the editor is still OOO for a bit.

**Comment by triple-underscore** [comment]
Added Japanese translation of File System:
https://fs.spec.whatwg.org/
at:
https://triple-underscore.github.io/fs-ja.html

**Comment by annevk** [comment]
That's great! I'll link it from the specification.
