### ISSUE TITLE
[translation request] BCP56bis

### ISSUE THREAD

**Issue by Jxck** [triple-underscore/triple-underscore.github.io#10]
Hi team

It's so great to have translate of the BCP56bis. It's a Best Current Practice of using HTTP for developer who use HTTP not for developer who build HTTP implementation by mnot.

- [Building Protocols with HTTP](https://httpwg.org/http-extensions/draft-ietf-httpbis-bcp56bis.html)

It would help developer working on web service.

Thanks
Jxck

**Comment by triple-underscore** [comment]
That is one of “todo” list.
OK, I'll try to translate it first, just began to translate it today.

**Comment by Jxck** [comment]
Awesome, thanks !!

**Comment by triple-underscore** [comment]
Now, the translation is available at:
https://triple-underscore.github.io/http-app-bcp-ja.html

**Comment by Jxck** [comment]
Cool ! Thanks so much for your delightful effort !!!
