### ISSUE TITLE
CSS module scriptsに関する日本語訳漏れ

### ISSUE THREAD

**Issue by mtrootyy** [triple-underscore/triple-underscore.github.io#11]
https://html.spec.whatwg.org/multipage/scripting.html#the-script-element
>Classic scripts and JavaScript module scripts can be embedded inline, or be imported from an external file using the src attribute, which if specified gives the URL of the external script resource to use. If src is specified, it must be a valid non-empty URL potentially surrounded by spaces.
>The contents of inline script elements, or the external script resource, must conform with the requirements of the JavaScript specification's Script or Module productions, for classic scripts and JavaScript module scripts respectively. [JAVASCRIPT]
>The contents of the external script resource for CSS module scripts must conform to the requirements of the CSS specification. [CSS]
>When used to include data blocks, 

 

https://triple-underscore.github.io/HTML-scripting-ja.html#the-script-element
>［ 古典スクリプト, JavaScript モジュールスクリプト ］どちらも、 インラインに埋め込むことも， src 属性を指定して 外部ファイルから取り込むこともできる。 この src 属性値は、 利用する外部スクリプトリソースの URL を与える — その値は、前後空白可の妥当かつ空でない URL でなければならない。
>［ インラインな script 要素 ／ 外部スクリプトリソース ］の内容は、［ 古典スクリプトの場合は JavaScript 仕様 [JAVASCRIPT] の Script 生成規則／ JavaScript モジュールスクリプトの場合は 同仕様の Module 生成規則 ］による要件に適合しなければならない。
>script 要素を，データブロックを含ませるために利用する場合：
 
 
両者を比較してみると、「The contents of the external script resource for CSS module scripts must.....」の訳が抜けているような気がするので、ご確認を。

**Comment by triple-underscore** [comment]
指摘ありがとうございます。修正しました。
