### ISSUE TITLE
[translation request] Sanitizer API

### ISSUE THREAD

**Issue by Jxck** [triple-underscore/triple-underscore.github.io#12]
[Sanitizer API](https://wicg.github.io/sanitizer-api/) is a security related new API which calling for consensus on [FPWD](https://lists.w3.org/Archives/Public/public-webappsec/2021Jul/0008.html) now. It says that Chrome / Firefox working on implement it.
So I believe it's wonderful for JP folks to see your translate here. Thanks !

**Comment by triple-underscore** [comment]
I read it briefly; it seems very interesting feature I had never known.
OK, I'll try to translate it.

**Comment by triple-underscore** [comment]
It took quite a while; the translation is now available at:
https://triple-underscore.github.io/html-sanitizer-api-ja.html

**Comment by Jxck** [comment]
Thanks !!
