### ISSUE TITLE
イベントハンドラ内容属性のリストの漏れ

### ISSUE THREAD

**Issue by mtrootyy** [triple-underscore/triple-underscore.github.io#13]
下記の両者を比較すると、翻訳の方では、oncontextlostとoncontextrestoredが漏れているのでご確認をお願いします。

https://triple-underscore.github.io/HTML-dom-ja.html#global-attributes
「次に挙げるイベントハンドラ内容属性は、どの HTML 要素上に指定してもよい：」のリスト

https://html.spec.whatwg.org/multipage/dom.html#global-attributes:event-handler-content-attributes
「The following event handler content attributes may be specified on any HTML element:」のリスト

**Comment by triple-underscore** [comment]
指摘ありがとうございます。更新漏れだったようです。修正しました。
