### ISSUE TITLE
[translation request] CBOR

### ISSUE THREAD

**Issue by Jxck** [triple-underscore/triple-underscore.github.io#15]
Hi Team

[CBOR](https://datatracker.ietf.org/doc/html/rfc8949) is the generic serialize format which referred by lots of specs now. (ex. WebAuthnN, Trust Token, etc etc etc)
It'd be happy for JP devs if your translations are published.

Thanks
Jack

**Comment by triple-underscore** [comment]
Well, I'll try to translate it.
(After I read it briefly,  I feel it would take about 3 weeks or more.)

**Comment by triple-underscore** [comment]
It took a long time; the translation is available at:
https://triple-underscore.github.io/CBOR-ja.html

**Comment by Jxck** [comment]
Excellent, thanks!!
