### ISSUE TITLE
[Infra Standard] 符号位置範囲の誤り

### ISSUE THREAD

**Issue by SaekiTominaga** [triple-underscore/triple-underscore.github.io#16]
「ASCII 16 進数字（大文字）」と「ASCII 英大文字」、「ASCII 英小文字」の範囲が原文と異なっていました。
https://triple-underscore.github.io/infra-ja.html#code-points

> ```diff
> ASCII 16 進数字（大文字）
> - { ASCII 数字, U+0061 (A) 〜 U+0066 (F) } 
> + { ASCII 数字, U+0041 (A) 〜 U+0046 (F) } 
> ```

> ```diff
> ASCII 英大文字
> - { U+0041 (A) 〜 U+0046 (Z) }
> + { U+0041 (A) 〜 U+005A (Z) }
> ```

> ```diff
> ASCII 英小文字
> - { U+0061 (a) 〜 U+0066 (Z) }
> + { U+0061 (a) 〜 U+007A (z) }
> ```

最後の「ASCII 英小文字」は Z → z の誤りもあります。
ご確認お願いします。

**Comment by triple-underscore** [comment]
ご指摘ありがとうございます。

https://github.com/triple-underscore/triple-underscore.github.io/commit/4c4d15c14a68026c8e435cace45f0a971c4783c6 にて修正しました。
