### ISSUE TITLE
「半角グリフ」

### ISSUE THREAD

**Issue by scivola** [triple-underscore/triple-underscore.github.io#17]
「6.1. 相対単位」の `ch` が

> 要素のフォントにおける半角グリフの代表的な[文字送り幅](https://triple-underscore.github.io/css-values-ja.html#length-advance-measure) — 文字 “0” （ U+0030 ZERO ）のグリフで表現される。

となっていますが，原文は

> typical character advance of a narrow glyph in the element’s font, as represented by the “0” (ZERO, U+0030) glyph

です。
「a narrow glyph」の訳として「半角グリフ」は妥当でないように思います。

**Comment by triple-underscore** [comment]
該当する訳語は見当たらないので、便宜上 "半角グリフ" と訳したのですが…

（それゆえ、訳文の中で "半角" が "narrow" の対訳であることを括弧内に明示的に示してもいます。
また、全角の "０" ではないので， "半角" 自体は誤った言明ではないと思いますが、
0 の送り幅を半角グリフの *代表的* な文字送り幅と見なすことには異論があるかもしれません。）

…が、より相応しいと考えられる訳語はありますか？

仮に "narrow" の意味を直に表すよう “狭いグリフ” 等と訳しても、
おそらく Unicode 仕様に利用される専門用語であり，
公式的な定義への明示的な参照が与えられていないので、
結局は "narrow" の対訳であることを明示的に示す必要はあるかと思います。

**Comment by scivola** [comment]
「半角」は基本的には全角（1 em）の半分を指す用語なので（つまり 0.5 em），寸法単位の話でこの用語を持ち出すのは誤解を招きやすいのでは，というのがこの issue の動機でした。

> 全角の "０" ではないので， "半角" 自体は誤った言明ではないと思いますが

おそらく，文字種として「半角」という言葉をお使いになったものと思います。
Shift JIS などにおける「1 バイト文字」とか Unicode における U+0020〜U+007E を指す「半角」ですね。

これらの文字を「半角（文字）」と呼ぶのは，かつてそれが実際に確実に半角（0.5 em）の幅で表示されるものであった名残でしょう。十分に定着した用法であり，誤解に気をつけながら使用することは，現在でもアリだと思います。

ただ，この文書では「半角グリフ」という形で出てきます。
グリフというのは特定のフォントの特定の文字について具体的にデザインしたものです。
したがって，「半角グリフ」といえば「0.5 em の幅を持ってデザインされたグリフ」以外に解釈のしようがないと私は思います。

6.1.1 で「半角（ narrow ）」という書き方がしてあるのは気づきませんでした，すみません。6.1 の表しか見てませんでした。

代案は思いつきません。
「細めのグリフ」あたりでしょうか。幅が小さいグリフは i, l やパンクチュエーションなど，0 よりもっと小さいものがたくさんあるので「め」が入っていた方がよさそうな気はします。
どのような訳語を当てるにしても原文が narrow glyph であることは示す必要があるでしょう。

**Comment by triple-underscore** [comment]
折衷案として、引用符を付けて "“半角” （narrow）グリフ" とするのはどうでしょう。

- 同じ文脈で対義的な用法として "全角" （ "fullwidth" ）が利用されており， "半角" の方がしっくりする（また、 "半角" の方が馴染まれている）
- "狭い", "幅が小さい" 等々では仰ったとおり語義が広くなり過ぎる
- それらが記された箇所において規範的な内容に関わるのは、特定の文字 "0", "水" であり， "narrow", "fullwidth" は参考情報にすぎない

からです。

ちなみに、前に述べたように、
原文の "narrow glyph" の "narrow" （および "fullwidth glyph" の "fullwidth" ）は，
Unicode [East Asian Width](https://www.unicode.org/reports/tr11/tr11-39.html) に述べられた分類が念頭にあるように思います
（そこでは、 narrow の一部を成す分類として halfwidth （ "半角" ）も挙げられていました）。
この場合、 "narrow glyph" は「 "narrow" に分類される文字用のグリフ」と解釈することになります（断定はできませんが）。
英文には、そのような省略表現は多々あることに加え、
仕様の実装者は、一般にデザイン用語ではなく Unicode 仕様を規範にすると思われるからです。
また、デザインとしての “狭い” も含めた両義的な意味を簡潔に表現しているとも解釈できます（そのような事例もよくあります）。

**Comment by scivola** [comment]
> 同じ文脈で対義的な用法として "全角" （ "fullwidth" ）が利用されており

私にはそのように読めませんでした（対義的に使われているとは思えなかった，の意）。
fullwidth も narrow width もいろいろな width の一つという認識です。

> 原文の "narrow glyph" の "narrow" （および "fullwidth glyph" の "fullwidth" ）は，
> Unicode [East Asian Width](https://www.unicode.org/reports/tr11/tr11-39.html) に述べられた分類が念頭にあるように思います

UAX #11 を見てみましたが，

* narrow ↔ wide
* halfwidth ↔ fullwidth

と対比しているように見えました（英語デキナイ人なので誤読でしたらすみません）。

ch のような単位が CSS に導入された経緯を全く知らないので推測になりますが，おそらく相対単位としてタイプフェースデザイン依存の単位が欲しいということがあるのでしょう。
垂直方向では ex が（ウェブ以前の）古い時代から使われてきています。
水平方向でも，幅広にデザインされたフォントでは大きくなり，狭くデザインされたフォントでは小さくなるような単位がタイポグラフィー上，求められていました。
（ちょっとややこしくなりますが，em をタイプフェース依存の単位とする組版システムもあります。これはもちろん CSS 標準の em とは必ずしも一致しません）
これは欧文の発想なので，UAX #11 が述べている「東アジア」の文字の話から来ているようには思えませんでした。
（いやまあ ic が同時に導入されていることから，全体として東アジアの文字も考えていることは確かですが）

「半角」が妥当と思えない理由は上のコメントで既に述べたとおりで，これ以上私にはうまく説明できません。
「半角グリフ」という用語が一人歩きすることを恐れています。
実際，「CSS の値と単位」の和訳の存在に気づいたのが，ch を「要素のフォントの半角グリフの文字送り幅の値」と書かれた記事を拝見したからでした。

「半角」を二重引用符を囲むことは誤解の可能性を少し小さくする効果があると思います。
ただ，世間で既に「半角」がこの意味（CSS の ch 的な意味）で使われているわけではないので（たぶん），「いわゆる」という意図ではないですよね。

**Comment by triple-underscore** [comment]
とりあえず、 narrow は訳さず原語のまま表記するよう更新しました。
同時に “対義的” な fullwidth も一貫性を重視して訳さないことにしました。
（言い換えれば、読者に丸投げですが。）

**Comment by scivola** [comment]
ありがとうございました。
私が close してしまってよいか分かりませんのでそのままにしますが，異存ありませんので，close でよろしければそうしていただければと思います。
（なお，ここで書くことではないかもしれませんが，私のような英語が苦手な者には和訳が存在することはたいへんありがたく，翻訳とメンテにお時間を割いてくださっていることに感謝いたします）

**Comment by triple-underscore** [comment]
こちらこそ、ご意見ありがとうございました。
他にもあれば、遠慮なくお願いします。
