### ISSUE TITLE
[translation request] Structured Field Values Bis

### ISSUE THREAD

**Issue by Jxck** [triple-underscore/triple-underscore.github.io#19]
Hi Team.

Thanks for translation work on [RFC8941 — Structured Field Values for HTTP（日本語訳）](https://triple-underscore.github.io/http-structured-fields-ja.html).

The HTTP Working Group  currently working on updating RFC 8941 (a.k.a SFbis), and it's almost finished, waiting for being RFC at IETF.

It's so welcome that your translation also up-to-date once RFC published.

Latest draft is v6 for now: https://datatracker.ietf.org/doc/draft-ietf-httpbis-sfbis/

Diff: https://github.com/httpwg/http-extensions/compare/draft-ietf-httpbis-sfbis-00...draft-ietf-httpbis-sfbis-06#diff-7deda72998584766a38c8f35730fe2e125faa9f948e856e607fdea06b633af3a

Thanks !

**Comment by triple-underscore** [comment]
The translation is actually almost finished, but holding off on publishing it until it is  published as RFC, because there are only a very limited number of (translated) specifications that refer to it.

Do you want the translation to be made public soon?

**Comment by Jxck** [comment]
Ah my fault.
We can keep waiting for publishing RFC.
Thanks!

**Comment by triple-underscore** [comment]
It is now available at the same URL as the existing translation of RFC 8941 (which is replaced with the new translation of RFC 9651).
