### ISSUE TITLE
[Media Queries Level 4] 「首ポインタ指示装置」は「主ポインタ指示装置」の誤字ですか？

### ISSUE THREAD

**Issue by geckotang** [triple-underscore/triple-underscore.github.io#4]
https://triple-underscore.github.io/mediaqueries4-ja.html#media-conditions

`primary`の訳が、 `主` になるところが `首` になっているようです。

```diff
- または 首ポインタ指示装置が hover 能力を有さない
+ または 主ポインタ指示装置が hover 能力を有さない
```

ここ以外の箇所でも、同じように`primary`の訳が`主`になるところが`首`になっているようですが、これらは誤字でしょうか？

**Comment by triple-underscore** [comment]
「首」は、「主」（ main 等）との意味合いの違い（首位／第一 vs. 主な／主要な）を表現するための意図的な対訳です（およそ、「第一」と「主な」を兼ねる／中間をとる感じ）。

主の方が馴染みやすいかもしれず、仕様や文脈によっては，そう対訳している箇所もありますが。

**Comment by geckotang** [comment]
意図を理解しました。納得できたので閉じます。
