### ISSUE TITLE
[HTML-form-elements] select要素の仮入力ラベル選択肢を決定するアルゴリズムが誤っている

### ISSUE THREAD

**Issue by takemar** [triple-underscore/triple-underscore.github.io#6]
https://triple-underscore.github.io/HTML-form-elements-ja.html#placeholder-label-option のselect要素の仮入力ラベル選択肢を決定するアルゴリズムですが、第4段で

> IF［ O の値 ＝ 空文字列 ］ RETURN ε 

となっているのは

> IF［ O の値 ≠ 空文字列 ］ RETURN ε 

が正しいのではないでしょうか。

**Comment by triple-underscore** [comment]
@takemar さん、
ご指摘のとおり誤っているようです。
↑修正しておきましたので、確認してみてください。

ありがとうごうざいました。
