### ISSUE TITLE
[Errata] Incorrect Table Values for Method Safe/Idempotent

### ISSUE THREAD

**Issue by Jxck** [triple-underscore/triple-underscore.github.io#9]
In https://triple-underscore.github.io/RFC7231-ja.html#section-8.1.3

Table says "POST" as Yes(safe) / Yes(Idempotent)
but Original RFC says **No** for both.

**Comment by triple-underscore** [comment]
Ah, it's my mistake. I fixed it in https://github.com/triple-underscore/triple-underscore.github.io/commit/b7dfca39dd6ba6e962d11146576c28948b72ddff
Thank you! @Jxck

**Comment by Jxck** [comment]
LGTM thanks !
